# Generated by Django 6.0.3 on 2026-04-06 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id_project', models.AutoField(primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('info_akadem', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'projects',
            },
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('login', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('someone_id', models.CharField(max_length=50, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('patronymic', models.CharField(blank=True, max_length=100, null=True)),
                ('student_group', models.CharField(max_length=20)),
                ('direction_name', models.CharField(max_length=100)),
                ('study_year', models.IntegerField(blank=True, null=True)),
                ('faculty', models.CharField(max_length=100)),
                ('study_score', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('debt_count', models.IntegerField(blank=True, null=True)),
                ('history_work_sem', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('history_work_week', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('history_work_all', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('history_work_mounth', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('top_view', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'students',
            },
        ),
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('team_id', models.AutoField(primary_key=True, serialize=False)),
                ('expert_score', models.CharField(blank=True, max_length=10, null=True)),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('project', models.ForeignKey(db_column='project_id', on_delete=django.db.models.deletion.CASCADE, to='LeaderBoard.projects')),
            ],
            options={
                'db_table': 'teams',
            },
        ),
        migrations.CreateModel(
            name='Student_Medals',
            fields=[
                ('medal_id', models.AutoField(primary_key=True, serialize=False)),
                ('grade', models.IntegerField()),
                ('medal_name', models.CharField(max_length=100)),
                ('award_date', models.DateField()),
                ('student', models.ForeignKey(db_column='student_login', on_delete=django.db.models.deletion.CASCADE, to='LeaderBoard.students')),
            ],
            options={
                'db_table': 'student_medals',
                'constraints': [models.CheckConstraint(condition=models.Q(('grade__gte', 1)), name='grade_gte_1')],
            },
        ),
        migrations.CreateModel(
            name='Student_Teams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('Студент', 'Студент'), ('Наставник', 'Наставник')], max_length=20)),
                ('joined_date', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(db_column='student_login', on_delete=django.db.models.deletion.CASCADE, to='LeaderBoard.students')),
                ('team', models.ForeignKey(db_column='team_id', on_delete=django.db.models.deletion.CASCADE, to='LeaderBoard.teams')),
            ],
            options={
                'db_table': 'student_teams',
                'constraints': [models.UniqueConstraint(fields=('team', 'student'), name='unique_team_student')],
            },
        ),
        migrations.CreateModel(
            name='Student_Activity',
            fields=[
                ('activity_id', models.AutoField(primary_key=True, serialize=False)),
                ('hours_weekly', models.DecimalField(decimal_places=1, max_digits=4)),
                ('weekly_period', models.DateField()),
                ('student', models.ForeignKey(db_column='student_login', on_delete=django.db.models.deletion.CASCADE, to='LeaderBoard.students')),
                ('team', models.ForeignKey(db_column='team_id', on_delete=django.db.models.deletion.CASCADE, to='LeaderBoard.teams')),
            ],
            options={
                'db_table': 'student_activity',
                'constraints': [models.UniqueConstraint(fields=('student', 'team', 'weekly_period'), name='unique_student_team_week'), models.CheckConstraint(condition=models.Q(('hours_weekly__gte', 0)), name='hours_weekly_non_negative')],
            },
        ),
    ]
