# Generated by Django 6.0.3 on 2026-04-14 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LeaderBoard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='history_work_mounth',
            new_name='history_work_month',
        ),
    ]
