# Generated by Django 6.0.5 on 2026-09-11 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LeaderBoard', '0004_students_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='rating_score',
            field=models.DecimalField(db_index=True, decimal_places=2, default=0, max_digits=8),
        ),
    ]
