# Generated by Django 6.0.5 on 2026-09-15 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LeaderBoard', '0006_alter_students_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='RatingSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, help_text='Итоговый рейтинговый балл', max_digits=8)),
                ('study_score', models.DecimalField(blank=True, decimal_places=1, help_text='Оценка успеваемости на момент расчёта', max_digits=3, null=True)),
                ('history_work_all', models.DecimalField(blank=True, decimal_places=2, help_text='Суммарные часы на момент расчёта', max_digits=10, null=True)),
                ('study_component', models.DecimalField(blank=True, decimal_places=6, help_text='Компонента успеваемости в рейтинге', max_digits=8, null=True)),
                ('work_component', models.DecimalField(blank=True, decimal_places=6, help_text='Компонента часов в рейтинге', max_digits=8, null=True)),
                ('formula_version', models.CharField(default='v1', help_text='Версия формулы расчёта', max_length=20)),
                ('reason', models.CharField(choices=[('manual_recalc', 'Ручной пересчёт'), ('weekly_recalc', 'Еженедельный пересчёт'), ('after_sync', 'После синхронизации'), ('formula_change', 'Изменение формулы'), ('admin_action', 'Действие администратора')], default='manual_recalc', help_text='Причина пересчёта', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(db_column='student_login', on_delete=django.db.models.deletion.CASCADE, related_name='rating_snapshots', to='LeaderBoard.students')),
            ],
            options={
                'db_table': 'rating_snapshots',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['student', '-created_at'], name='rating_snap_student_155c3c_idx')],
            },
        ),
    ]
