# Generated by Django 6.0.5 on 2026-09-20 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LeaderBoard', '0007_ratingsnapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='rating_score_month',
            field=models.DecimalField(db_index=True, decimal_places=2, default=0, help_text='Рейтинг за месяц', max_digits=8),
        ),
        migrations.AddField(
            model_name='students',
            name='rating_score_sem',
            field=models.DecimalField(db_index=True, decimal_places=2, default=0, help_text='Рейтинг за семестр', max_digits=8),
        ),
        migrations.AddField(
            model_name='students',
            name='rating_score_week',
            field=models.DecimalField(db_index=True, decimal_places=2, default=0, help_text='Рейтинг за неделю', max_digits=8),
        ),
        migrations.AlterField(
            model_name='students',
            name='rating_score',
            field=models.DecimalField(db_index=True, decimal_places=2, default=0, help_text='Рейтинг за всё время', max_digits=8),
        ),
    ]
