# Generated by Django 6.0.5 on 2026-09-20 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LeaderBoard', '0008_students_rating_score_month_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Код источника (например, TPU, VITRINA)', max_length=50, unique=True)),
                ('name', models.CharField(help_text='Название источника', max_length=100)),
                ('base_url', models.URLField(blank=True, help_text='Базовый URL API', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Источник активен')),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Внешний источник',
                'verbose_name_plural': 'Внешние источники',
                'db_table': 'external_sources',
            },
        ),
        migrations.CreateModel(
            name='SyncRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(help_text='Название задачи (например, sync_tpu_students)', max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('running', 'Выполняется'), ('success', 'Успешно'), ('failed', 'Ошибка'), ('partial_success', 'Частично успешно')], default='pending', max_length=20, verbose_name='Статус')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Начало')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Окончание')),
                ('records_received', models.IntegerField(default=0, verbose_name='Получено записей')),
                ('records_created', models.IntegerField(default=0, verbose_name='Создано')),
                ('records_updated', models.IntegerField(default=0, verbose_name='Обновлено')),
                ('records_skipped', models.IntegerField(default=0, verbose_name='Пропущено')),
                ('records_failed', models.IntegerField(default=0, verbose_name='Ошибок')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Сообщение об ошибке')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_runs', to='LeaderBoard.externalsource', verbose_name='Источник')),
            ],
            options={
                'verbose_name': 'Запуск синхронизации',
                'verbose_name_plural': 'Запуски синхронизации',
                'db_table': 'sync_runs',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='SyncError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(blank=True, help_text='Внешний ID записи (login, id_project и т.д.)', max_length=100, null=True)),
                ('payload', models.JSONField(blank=True, help_text='Данные, которые не удалось обработать', null=True, verbose_name='Исходные данные')),
                ('error_message', models.TextField(verbose_name='Сообщение об ошибке')),
                ('error_type', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sync_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='errors', to='LeaderBoard.syncrun', verbose_name='Запуск синхронизации')),
            ],
            options={
                'verbose_name': 'Ошибка синхронизации',
                'verbose_name_plural': 'Ошибки синхронизации',
                'db_table': 'sync_errors',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RawApiLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(max_length=255, verbose_name='Endpoint')),
                ('request_params', models.JSONField(blank=True, null=True, verbose_name='Параметры запроса')),
                ('request_body', models.JSONField(blank=True, null=True, verbose_name='Тело запроса')),
                ('status_code', models.IntegerField(blank=True, null=True, verbose_name='HTTP статус')),
                ('response_body', models.JSONField(blank=True, null=True, verbose_name='Тело ответа')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Ошибка')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_logs', to='LeaderBoard.externalsource', verbose_name='Источник')),
                ('sync_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='raw_logs', to='LeaderBoard.syncrun', verbose_name='Запуск синхронизации')),
            ],
            options={
                'verbose_name': 'Сырой лог API',
                'verbose_name_plural': 'Сырые логи API',
                'db_table': 'raw_api_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='syncrun',
            index=models.Index(fields=['source', '-started_at'], name='sync_runs_source__7f22d9_idx'),
        ),
        migrations.AddIndex(
            model_name='syncrun',
            index=models.Index(fields=['status'], name='sync_runs_status_08b30a_idx'),
        ),
        migrations.AddIndex(
            model_name='syncerror',
            index=models.Index(fields=['sync_run', '-created_at'], name='sync_errors_sync_ru_b93e74_idx'),
        ),
        migrations.AddIndex(
            model_name='rawapilog',
            index=models.Index(fields=['source', '-created_at'], name='raw_api_log_source__3d2e31_idx'),
        ),
        migrations.AddIndex(
            model_name='rawapilog',
            index=models.Index(fields=['sync_run'], name='raw_api_log_sync_ru_887448_idx'),
        ),
    ]
