# Generated by Django 6.0.5 on 2026-10-01 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LeaderBoard', '0009_externalsource_syncrun_syncerror_rawapilog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='category',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='projects',
            name='external_id',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='is_promoted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projects',
            name='partner',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='projects',
            name='project_type',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='projects',
            name='status',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='student_teams',
            name='stack',
            field=models.CharField(blank=True, help_text='Профессиональная роль: Frontend, Backend, Mobile, ML-инженер, QA, Аналитик и т.д.', max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='ProjectCheckpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(blank=True, max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('deadline', models.DateField()),
                ('is_custom', models.BooleanField(default=False)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkpoints', to='LeaderBoard.projects')),
            ],
            options={
                'db_table': 'project_checkpoints',
                'unique_together': {('project', 'title')},
            },
        ),
    ]
