# Generated by Django 6.0.5 on 2026-10-01 14:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LeaderBoard', '0010_projects_category_projects_external_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='projects',
            index=models.Index(fields=['project_type', 'status'], name='projects_project_627aa0_idx'),
        ),
        migrations.AddIndex(
            model_name='projects',
            index=models.Index(fields=['category'], name='projects_categor_a66ca2_idx'),
        ),
        migrations.AddIndex(
            model_name='projects',
            index=models.Index(fields=['-is_promoted', 'project_name'], name='projects_is_prom_88d145_idx'),
        ),
        migrations.AddIndex(
            model_name='students',
            index=models.Index(fields=['student_group', '-rating_score'], name='students_student_4c3248_idx'),
        ),
        migrations.AddIndex(
            model_name='students',
            index=models.Index(fields=['study_year', '-rating_score'], name='students_study_y_6b0840_idx'),
        ),
        migrations.AddIndex(
            model_name='students',
            index=models.Index(fields=['faculty', '-rating_score'], name='students_faculty_da4909_idx'),
        ),
        migrations.AddIndex(
            model_name='students',
            index=models.Index(fields=['-rating_score_week'], name='students_rating__efa115_idx'),
        ),
        migrations.AddIndex(
            model_name='students',
            index=models.Index(fields=['-rating_score_month'], name='students_rating__fcdf1c_idx'),
        ),
        migrations.AddIndex(
            model_name='students',
            index=models.Index(fields=['-rating_score_sem'], name='students_rating__14075d_idx'),
        ),
    ]
